### ISSUE TITLE
XML布局找不到对应的id

### ISSUE THREAD

**Issue by luhaikong** [MingYueChunQiu/RecorderManager#1]
楼主你好，我在使用你的库的时候，编译出现问题，报如下错误，因为你的“@”和“id”之间缺少“+”造成的，希望楼主能够优化一下。

Error:(24, 46) No resource found that matches the given name (at 'layout_constraintBottom_toTopOf' with value '@id/cpb_record_video_record').
Error:(71, 46) No resource found that matches the given name (at 'layout_constraintRight_toLeftOf' with value '@id/iv_record_video_confirm').
Error:(24, 46) No resource found that matches the given name (at 'layout_constraintBottom_toTopOf' with value '@id/cpb_record_video_record').
Error:(71, 46) No resource found that matches the given name (at 'layout_constraintRight_toLeftOf' with value '@id/iv_record_video_confirm').

**Comment by MingYueChunQiu** [comment]
布局用的是ConstraintLayout，这儿@id都是引用前面已经定义过的android:id="@+id/xxx"，你的项目里依赖了implementation 'com.android.support.constraint:constraint-layout:1.1.3'吗？我在其他项目里依赖库没有问题
