### ISSUE TITLE
想问一下设置视频品质的参数是在哪个文件

### ISSUE THREAD

**Issue by loquitowen** [MingYueChunQiu/RecorderManager#10]
想问一下设置视频品质的参数是在哪个文件

**Comment by MingYueChunQiu** [comment]
在RecorderOption里，目前直接用提供的api调用现有样式的录制界面没有提供配置入口，后期会添加，目前你可以直接调用RecordVideoFragment ，现有直接调用的录制界面就是包裹了一个RecordVideoFragment

**Comment by MingYueChunQiu** [comment]
新的0.2.28版本已经加入RecorderOption配置了，详情可以看下文档

**Comment by loquitowen** [comment]
感谢------------------ 原始邮件 ------------------
发件人: "MingYueChunQiu"<notifications@github.com>
发送时间: 2019年10月27日(星期天) 中午1:37
收件人: "MingYueChunQiu/RecorderManager"<RecorderManager@noreply.github.com>;
抄送: "loquito"<mosquito.ix@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MingYueChunQiu/RecorderManager] 想问一下设置视频品质的参数是在哪个文件 (#10)



新的0.2.28版本已经加入RecorderOption配置了，详情可以看下文档
 
&mdash;
