### ISSUE TITLE
录像像设置为横屏，请问如何实现？

### ISSUE THREAD

**Issue by loquitowen** [MingYueChunQiu/RecorderManager#11]
录像像设置为横屏，请问如何实现？
不好意思，又来打搅了。

**Comment by MingYueChunQiu** [comment]
在关闭的issue里有这个问题，可以去看看，目前没有api直接调用横屏，可以照着RecordActivity写一个去包裹RecordVideoFragment，然后在配置清单里设置横屏，但是样式什么的可能不对，最好把库里feature下的main包直接复制过去改样式
