### ISSUE TITLE
1视频录制镜像问题 2 点按钮录制时视频画面会放大跳动一下，录制完会缩小

### ISSUE THREAD

**Issue by Leavds** [MingYueChunQiu/RecorderManager#12]

**Comment by MingYueChunQiu** [comment]
镜像问题是指前置摄像头录下来的和播放的左右相反那个吗，库没有做相关处理，手机自带的相机app的前置摄像头录出来也都是这样的。
至于第二个录制时会动一下是因为它从预览状态进入录制状态，手机自带录制也是这样的，录制完会缩小，是因为界面开始播放录制完的视频，而库默认配置的分辨率是比较低的，这样录制出的视频体积小，你可以自己配置改分辨率等信息。
