### ISSUE TITLE
设置视频宽高崩溃

### ISSUE THREAD

**Issue by Roben1016** [MingYueChunQiu/RecorderManager#13]
通过RecorderOption设置了视频的宽高会闪退; 另外这个按下按钮时的提示音可以取消吗, 怎么取消呢

**Comment by Roben1016** [comment]
RecorderOption这个配置, 设置有什么要求吗, 各种崩溃

**Comment by MingYueChunQiu** [comment]
按下按钮的声音是系统发出的，有的手机有有的没有，有时间我看一下。
你是调用录制界面进行录制，还是自己使用RecorderManagerFactory进行录制，默认提供的录制界面里面提供的是默认的这个方法
public RecorderOption buildDefaultVideoBean(String path) {
            return this.setAudioSource(MediaRecorder.AudioSource.CAMCORDER)
                    .setVideoSource(MediaRecorder.VideoSource.CAMERA)
                    .setOutputFormat(MediaRecorder.OutputFormat.MPEG_4)
                    .setAudioEncoder(MediaRecorder.AudioEncoder.AAC)
                    .setVideoEncoder(MediaRecorder.VideoEncoder.H264)
                    .setVideoWidth(640)
                    .setVideoHeight(480)
                    .setBitRate(3 * 1024 * 1024)
                    .setFrameRate(30)
                    .setOrientationHint(90)
                    .setFilePath(path)
                    .build();
        }
视频的帧率和视频大小是需要硬件支持的，如果设置的帧率和视频大小,如果硬件不支持就会出现错误，后期有时间我看看容错适配。

**Comment by Roben1016** [comment]
嗯, 后面我调整了一下, 原来录制出来的视频太模糊了, 现在ok了, 还有就是有没有方法支持拍照

**Comment by MingYueChunQiu** [comment]
当初目的是专门用于录制的，没有写拍照这个功能，后面版本的话会考虑加上，目前的话，可以先引用库，然后把库里的feature.main包下的复制到自己项目里，自己写个按钮或改一下按钮的相关处理，要自己写了。

**Comment by Roben1016** [comment]
好的, 感谢
