### ISSUE TITLE
部分手机长按提示“录制时间小于1秒，请重试”

### ISSUE THREAD

**Issue by Roben1016** [MingYueChunQiu/RecorderManager#17]
出现过好几个，基本都是华为的全面屏手机：
华为nova5z 华为Mate9等等
下图是两外的两个手机参数信息，麻烦帮忙看下是什么原因呢
![视频录制](https://user-images.githubusercontent.com/15700182/83509880-b1cef400-a4fe-11ea-91f4-ba98fc2fbfaf.jpg)
![录制视频1](https://user-images.githubusercontent.com/15700182/83510009-e3e05600-a4fe-11ea-9f46-632effd755ba.jpg)

**Comment by Roben1016** [comment]
大佬, 有空帮忙看下吧, 实在没找到原因

**Comment by MingYueChunQiu** [comment]
长按后不到1秒就抬起手指，会弹这个提示，你是在这些手机上试了长按超过了1秒，上面计时也显示超过了1秒，然后弹的这个提示吗？

**Comment by Roben1016** [comment]
@MingYueChunQiu 我没有试出来, 是有一部分用户试过, 并且确定自己是长按, 从他们录制的视频也可以看出确实是长按的

**Comment by MingYueChunQiu** [comment]
我这没有你的那两款手机，找了华为P30还有其他手机试了下，没有出现这个现象，我抽空再看看，那些用户录制弹toast失败了，但是在保存路径下出现了正常录制时长且播放正常的视频了是吗？

**Comment by Roben1016** [comment]
@MingYueChunQiu 看他们录制的视频好像是没有录制成功, 有没有联系方式, 我这有个用户录制的视频, 看他是一直按住不动, 一秒就提示错误, 也没有预览视频, 应该是没录制成功

**Comment by MingYueChunQiu** [comment]
那到csdn https://blog.csdn.net/sl2018god/article/details/86693632上，发私信给我，我发QQ给你
