### ISSUE TITLE
怎么覆盖录制按钮的单机事件

### ISSUE THREAD

**Issue by TSsimeon** [MingYueChunQiu/RecorderManager#18]
录制按钮单击出现等待出现录制小于1s，长按才会进入正常录制。

**Comment by MingYueChunQiu** [comment]
因为目前只有长按录制功能，所以按下到抬起是一次事件，如果录制时长小于1秒会有崩溃风险，你的需求是什么，是单击开始录制，再点击停止录制吗？

**Comment by TSsimeon** [comment]
嗯嗯。需求就是点击可以录制。我现在换成原生方式加压缩实现了。有时间可以改一下大佬。体验感觉会好一点。

**Comment by MingYueChunQiu** [comment]
好，会考虑增加一种录制模式

**Comment by TSsimeon** [comment]
谢谢。可以的大佬！

**Comment by MingYueChunQiu** [comment]
客气了
