### ISSUE TITLE
作者你好！请问如果我想改变视频的音源应该怎么做呢

### ISSUE THREAD

**Issue by HarryPotterr** [MingYueChunQiu/RecorderManager#21]
1.我想录制的时候用自己的音源
2.我想设置最小的录制时间限制

**Comment by MingYueChunQiu** [comment]
RecorderOption类可以配置MediaRecorder 所支持的private int audioSource;//音频源，设置最小录制时间，计划在之后版本中添加，目前只能将库下载到本地进行更改

**Comment by MingYueChunQiu** [comment]
v0.3.1版本现已增加设置最小的录制时间功能
