### ISSUE TITLE
作者你好，请问录像快门声音可以关闭么？

### ISSUE THREAD

**Issue by zjl1990518zjl** [MingYueChunQiu/RecorderManager#23]
录像的时候，在一些机型上(比如小米)，开始录音和结束录音的时候都会滴一声，请问下有办法可以关闭这个快门提示音么？

**Comment by MingYueChunQiu** [comment]
该问题属于一种防偷拍的潜规则类型设置，与android系统提供商相关，拍照／摄像的提示音所有实现都在底层实现，上层能够控制的有限。https://segmentfault.com/a/1190000002686247 这篇文章介绍的比较详细
