### ISSUE TITLE
大佬，能全部用java录制吗  不用kt。是kt录制有什么优势吗

### ISSUE THREAD

**Issue by Rain168** [MingYueChunQiu/RecorderManager#25]

**Comment by MingYueChunQiu** [comment]
0.2.x版本包括之前应该都是java代码，至于kotlin的好处录制这块都一样，可以换成java，其他好处代码量的减少，语法糖的使用等等，网上都有，每个人都有自己的见解，多学门语言还是好的，毕竟android现在推kotlin
