### ISSUE TITLE
app_name

### ISSUE THREAD

**Issue by sunjiejain** [MingYueChunQiu/RecorderManager#26]
为什么依赖之后,app_name会被你的app_name覆盖

**Comment by MingYueChunQiu** [comment]
库做了国际化，里面有英语和简体中文，value / value-zh，你可以添加对应语言的资源或者在manifest文件里处理，下个版本我会把app_name这个资源去掉

**Comment by MingYueChunQiu** [comment]
v0.3.2已移除app_name资源

**Comment by sunjiejain** [comment]
好的,当时我是把自己项目也做了国际化 , 就处理好了
