### ISSUE TITLE
录制时长set无效

### ISSUE THREAD

**Issue by MikeVoy** [MingYueChunQiu/RecorderManager#27]
按着您原Demo 调用  .setMaxDuration(60) 为什么还是30秒 然后我在 RecorderManagerConstants 和 option的默认Duration  直接改成60秒 录制时还是30秒  请问  set配置信息  这块是有问题吗

**Comment by MingYueChunQiu** [comment]
可以啊，我简单尝试了一下，没有问题
RecorderManagerFactory.getRecordVideoRequest().startRecordVideo(this, 0, RecordVideoRequestOption.Builder()
                    .setMaxDuration(10)
                    .build())
你的设置代码是什么样的

**Comment by MikeVoy** [comment]
我是下了您的demo 调了参数           RecorderManagerFactory.getRecordVideoRequest().startRecordVideo(TestFragment.this, 0,
                        new RecordVideoRequestOption.Builder()
                                .setMaxDuration(60)
                                .setRecordVideoOption(new RecordVideoOption.Builder()
//                                        .setHideFlipCameraButton(true)
//                                        .setHideFlashlightButton(true)
                                        .setMinDuration(2)
                                        .setMaxDuration(60)
                                        .setRecordVideoButtonOption(new RecordVideoButtonOption.Builder()
                                             .setIdleCircleColor(Color.WHITE) //空闲状态内部圆形颜色
                                              //  .setPressedRingColor(Color.YELLOW)//按下状态外部圆环颜色
                                                .build())
//                                        .setCameraType(RecorderManagerConstants.CameraType.CAMERA_FRONT)
                                        .setTimingHint("倒计时")
                                        .setErrorToastMsg("出错了")
                                        .setMaxDuration(60)
                                        .build())
                                .build()
                );

**Comment by MikeVoy** [comment]
我自己手动写的RecorderManagerFactory.getRecordVideoRequest().startRecordVideo(TestFragment.this, 0,new RecordVideoRequestOption.Builder().setMaxDuration(60).build());  还是无效 
>

**Comment by MingYueChunQiu** [comment]
我这边直接测试运行代码，修改参数在不同手机上都是正常的，我不清楚你那边是否还做了别的处理。既然你已经把项目下下来了，那只能直接运行dmeo，打断点跟踪看下数据究竟在哪一步发生了改变
