### ISSUE TITLE
录制视频后。视频镜像反转

### ISSUE THREAD

**Issue by RainQuKong** [MingYueChunQiu/RecorderManager#28]
你好，请问一下，如果不使用libyuv库 进行镜像反转的话，还有什么方法解决前置摄像头录制视频后，视频呈现镜像反转的问题，有没有尽量使用原生的API解决的方法？

**Comment by MingYueChunQiu** [comment]
可以找一下对应的镜像算法，后期版本有时间的话会研究加上
