### ISSUE TITLE
录制完毕,预览视频,视频被拉伸

### ISSUE THREAD

**Issue by sunjiejain** [MingYueChunQiu/RecorderManager#30]

**Comment by MingYueChunQiu** [comment]
目前选取的录制视频宽高比，是在RecorderManager类调用CameraParamsUtils.getInstance().getSupportSize算法，获取设备支持的最大分辨率的最接近相似比来处理，如果不满足你的需求或者有更好的方式，可以帮忙继续完善

**Comment by sunjiejain** [comment]
好的  谢谢作者

**Comment by sunjiejain** [comment]
那预览视频是哪个控件呢

**Comment by MingYueChunQiu** [comment]
主要逻辑在RecorderManager类，可以下载项目到本地，创建新类实现IRecorderManager， 拷贝RecorderManager里内容进行修改

**Comment by silveryTitan** [comment]
@sunjiejain 请问有解决方法了吗
