### ISSUE TITLE
设置视频地址后拍摄视频不能结束

### ISSUE THREAD

**Issue by liaoyanping** [MingYueChunQiu/RecorderManager#31]
RecordVideoRequestOption option = new RecordVideoRequestOption.Builder()
                            .setMaxDuration(15)
//                            .setFilePath(DownloadFilePath.getRecordVideoPath(MainActivity.this))
                            .build();
                    RecorderManagerFactory.getRecordVideoRequest().startRecordVideo(MainActivity.this, 1001, option);

**Comment by MingYueChunQiu** [comment]
请问你设置的文件路径是在哪儿，是否有权限操作此路径文件，如果直接使用默认配置的路径能正常使用吗
