### ISSUE TITLE
自动录制及自动保存

### ISSUE THREAD

**Issue by shenglei10** [MingYueChunQiu/RecorderManager#33]
你好！我是安卓新人。
想问下
1、用系统视频录制的话怎么让它录完直接保存，不需要我的确认。
2、怎么让它录完一个视频自动录下一个视频。
期待你的回复，感谢你的源码！

**Comment by MingYueChunQiu** [comment]
1.调用系统录制的话，可以使用Intent intent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);
                //设置视频录制的最长时间
                intent.putExtra(MediaStore.EXTRA_DURATION_LIMIT, 20);
                //设置视频录制的画质
                intent.putExtra(MediaStore.EXTRA_VIDEO_QUALITY, 1);
            intent.putExtra(MediaStore.EXTRA_OUTPUT, uri);//指定保存路径
            startActivityForResult(intent, REQ_2);//appcompat新版本采用registerForActivityResult
2.未遇到过，不太清楚

**Comment by lolkt** [comment]
@shenglei10 您好，实现自动录制下一个了吗?

**Comment by MingYueChunQiu** [comment]
自动录制下一个视频，这个需要下载源码修改代码，将录制完成后的播放状态这一过程跳过恢复到重置状态即可，但是目前操作流程是要用户按住按钮进行录制，自动录制视频，这个按住按钮这一块的交互逻辑考虑过怎么处理吗
