### ISSUE TITLE
你好，请问预览视频长宽比怎么控制

### ISSUE THREAD

**Issue by uHone** [MingYueChunQiu/RecorderManager#34]
全面屏手机视频拉伸严重，如何根据机型适配长宽比或者能否直接全部按照16：9的处理 不做拉伸，我复制了RecorderManager类修改了videoRatio 没有效果

**Comment by MingYueChunQiu** [comment]
RecorderManager里调用了CameraParamsUtils 类分辨率算法获取相应数据，下载项目更改该类里的方法
