### ISSUE TITLE
录制的时候被拉伸

### ISSUE THREAD

**Issue by uudon** [MingYueChunQiu/RecorderManager#39]
打开摄像头的时候，是正常的，但是点击录制按钮，整个画面被拉伸了

**Comment by MingYueChunQiu** [comment]
目前选取的录制视频宽高比，是在RecorderManager类调用CameraParamsUtils.getInstance().getSupportSize算法，获取设备支持的最大分辨率的最接近相似比来处理，目前比较忙，没有时间进一步完善，如果不满足你的需求或者有更好的方式，可以帮忙继续完善

**Comment by Mrliandroid** [comment]
我目前也存在这个问题。在相册查看的时候有点拉伸了。
