### ISSUE TITLE
可否提供一个横屏的RecordVideoActivity

### ISSUE THREAD

**Issue by guoai2015** [MingYueChunQiu/RecorderManager#4]
首先感谢作者，这个控件非常好。现在有个项目是平板端的，客户要求横屏，我试着继承RecordVideoActivity自己写了个Activity设置方向为横屏，但是界面是横过来了，摄像头预览并没有旋转。希望作者帮个忙。再次感谢！

**Comment by MingYueChunQiu** [comment]
我在CameraInterceptable里新增加了/**
     * 拦截相机预览方向
     *
     * @param degrees 预览相机角度（竖屏设置90，横屏设置0）
     * @return 返回相机的预览方向角度
     */
    int interceptCameraDisplayOrientation(int degrees);
你可以直接继承RecorderManagerIntercept，将这个方法返回值改为0，横屏预览就正常了。

它在RecorderManager的initCameraParameters方法里起作用，
        int degrees = 90;//默认竖屏旋转
        if (mIntercept != null) {
            degrees = mIntercept.interceptCameraDisplayOrientation(degrees);
        }
        mCamera.setDisplayOrientation(degrees);

拦截器的添加在RecorderManagerFactory的方法里，如果直接用我的界面可能不好走到这儿，你可以把库里main包直接复制到自己的项目里改改

**Comment by guoai2015** [comment]
好的，谢谢！
