### ISSUE TITLE
视频预览变形

### ISSUE THREAD

**Issue by Ysrfengnull** [MingYueChunQiu/RecorderManager#5]
录制是写死了分辨率，导致预览视频变形怎么处理

**Comment by MingYueChunQiu** [comment]
目前是从手机所支持的分辨率中选取最高分辨率进行录制显示效果较好，在CameraParamsUtils中可以找到这部分，最好是按照手机比例来选择分辨率可以解决这个问题，但目前有些兼容性问题，后期版本会去调整，目前只能你去复制库中RecorderManager的代码，改里面的逻辑

**Comment by MingYueChunQiu** [comment]
0.2.20版本对录制时界面效果做了一些优化，希望能不断完善

**Comment by Ysrfengnull** [comment]
ok
