### ISSUE TITLE
setParameters RuntimeException

### ISSUE THREAD

**Issue by yyloveruancaipu** [MingYueChunQiu/RecorderManager#7]
RuntimeException if any parameter is invalid or not supported.

**Comment by MingYueChunQiu** [comment]
呃，能否描述清楚一些，什么情况发生的什么问题，库是最新的版本吗？

**Comment by yyloveruancaipu** [comment]
android.hardware.Camera.native_setParameters(Native Method)
--
2 android.hardware.Camera.setParameters(Camera.java:2305)
3 com.mingyuechunqiu.recordermanager.feature.record.RecorderManager.initCameraParameters(RecorderManager.java:281)
4 com.mingyuechunqiu.recordermanager.feature.record.RecorderManager.initCamera(RecorderManager.java:169)
5 com.mingyuechunqiu.recordermanager.feature.record.RecorderManager.flipCamera(RecorderManager.java:200)
6 com.mingyuechunqiu.recordermanager.feature.record.RecorderManager.flipCamera(RecorderManager.java:189)
7 com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoPresenter.flipCamera(RecordVideoPresenter.java:175)
8 com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoFragment.onClick(RecordVideoFragment.java:174)
9 android.view.View.performClick(View.java:6323)
10 android.view.View$PerformClick.run(View.java:25124)

setParameters 报 RuntimeException 
是上一个版本，我这边业务需要：我要在视频录制的时候添加一个随机码。

**Comment by MingYueChunQiu** [comment]
你是自己调用RecorderManagerable进行录制的吗，没有像RecorderManagerFactory.getRecordVideoRequest().startRecordVideo(MainActivity.this, 0)这样启动页面，

在initCameraParameters里库是遍历所有机器支持的分辨率选择和界面比例最接近的最高分辨率，逻辑是没有问题的，你要在视频录制的时候添加一个随机码，是什么意思，是自己在外边添加还是插入到这些步骤中？上一个版本是指0.2.24吗？

你可以将库里RecorderManager和它用到的类复制出来写个demo测试一下，应该是没有问题的

**Comment by yyloveruancaipu** [comment]
是这样子的，我把你library集成到我项目里面去了，RecorderManagerFactory.getRecordVideoRequest().startRecordVideo(MainActivity.this, 0)是这样开启。随机码是我这边要做视频认证的一个业务需求，不影响。我自己手机没什么问题的，刚刚的日志是bugly反馈过来的。
就是 setParameters 报 RuntimeException

**Comment by MingYueChunQiu** [comment]
报错手机机型、系统版本有吗

**Comment by yyloveruancaipu** [comment]
Android 8.1.0,level 27
VIVO X21I A
arm64-v8a

**Comment by yyloveruancaipu** [comment]
兼容性问题比较大，这个问题出现了蛮多次了

**Comment by MingYueChunQiu** [comment]
我没有找到VIVO X21i A的手机，只找到几款VIVO X21 A，x27，x9i的测试过，没发现任何兼容性问题，你那边用VIVO X21I A真机测过吗，如果方便的话你可以尝试直接复制库中的RecorderManager，直接在initCameraParameters方法里选个分辨率来试，我这边测了很多机型确实没发现任何兼容性问题
